commerce_order.commerce_order_type.*:
  type: config_entity
  label: 'Order type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    workflow:
      type: string
      label: 'Workflow'

commerce_order.commerce_line_item_type.*:
  type: config_entity
  label: 'Line item type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    purchasableEntityType:
      type: string
      label: 'Purchasable entity type'
    orderType:
      type: string
      label: 'Order type'
