commerce_tax.commerce_tax_type.*:
  type: config_entity
  label: 'Tax type'
  mapping:
    id:
      type: string
      label: 'Tax type id'
    name:
      type: string
      label: 'Tax type name'
    genericLabel:
      type: string
      label: 'Tax type generic label'
    zone:
      type: string
      label: 'Tax type zone'
    compound:
      type: boolean
      label: 'Whether the tax type is compound'
    displayInclusive:
      type: boolean
      label: 'Whether the tax type is display inclusive'
    roundingMode:
      type: integer
      label: 'Tax type rounding mode'
    tag:
      type: string
      label: 'Tax type tag'
    rates:
      type: sequence
      label: 'Tax rates'
      sequence:
        - type: string

commerce_tax.commerce_tax_rate.*:
  type: config_entity
  label: 'Tax rate'
  mapping:
    id:
      type: string
      label: 'Tax rate id'
    type:
      type: string
      label: 'Tax type'
    name:
      type: string
      label: 'Tax rate name'
    default:
      type: boolean
      label: 'Whether the tax rate is the default for its tax type.'
    amounts:
      type: sequence
      label: 'Tax rate amounts'
      sequence:
        - type: string

commerce_tax.commerce_tax_rate_amount.*:
  type: config_entity
  label: 'Tax rate amount'
  mapping:
    id:
      type: string
      label: 'Tax rate amount id'
    rate:
      type: string
      label: 'Tax rate'
    amount:
      type: float
      label: 'Tax rate amount'
    startDate:
      type: date_format
      label: 'Tax rate amount start date'
    endDate:
      type: date_format
      label: 'Tax rate amount end date'
