commerce_store.commerce_store_type.*:
  type: config_entity
  label: 'Store type config'
  mapping:
    id:
      type: string
      label: 'Type'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    description:
      type: text
      label: 'Description'

commerce_store.settings:
  type: config_object
  label: 'Commerce Store settings'
  mapping:
    default_store:
      type: string
      label: 'Default store UUID'

views.field.commerce_store:
  type: views.field.field
  mapping:
    hide_single_store:
      type: boolean
      label: 'Hide if there''s only one store.'
